version: '3.4'

networks:
  app:

services:
#   postgres:
#     image: postgres
#     environment:
#       POSTGRES_USER: "postgres"
#       POSTGRES_DB: "pedidos"
#       POSTGRES_PASSWORD: "senha-ms"
#     volumes:
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     ports:
#       - "5432:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5
#     networks:
#       - app

  pedidos-ms:
    image: mauriciohm/production-ms:latest
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - app

